FROM ubuntu:latest

# Install Java 21, plus required tools
RUN apt-get update -qy && apt-get install -y \
    openjdk-21-jdk \
    maven \
    git \
    python3 \
    python3-pip \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*

# Setup Jenkins user (if needed)
RUN useradd -ms /bin/bash jenkins && echo "jenkins:jenkins" | chpasswd

# Setup SSH for agent connections
RUN mkdir -p /var/run/sshd

EXPOSE 8080 50000 22

CMD ["/usr/sbin/sshd", "-D"]
