FROM ubuntu:latest

# Install dependencies
RUN apt-get update -qy && apt-get install -qy \
    python3 \
    python3-pip \
    openjdk-11-jre \
    maven \
    git \
    openssh-server && \
    mkdir -p /var/run/sshd && \
    sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd && \
    rm -rf /var/lib/apt/lists/*

# Create Jenkins user
RUN useradd -ms /bin/bash jenkins && echo "jenkins:jenkins" | chpasswd

# Expose SSH port
EXPOSE 22

# Start SSH server in the foreground
CMD ["/usr/sbin/sshd", "-D"]
